package com.solar.launcher;

import com.solar.launcher.media.MediaSuiteHost;

/** Stable row identifiers for settings UI (locale-independent). */
public final class RowKeys {
    public static final String SHUFFLE = "settings.shuffle";
    public static final String REPEAT = "settings.repeat";
    public static final String EQ = "settings.eq";
    public static final String PLAYBACK = "settings.playback";
    public static final String BUTTON_SOUND = "settings.button_sound";
    public static final String BUTTON_VIBRATE = "settings.button_vibrate";
    public static final String SCREEN_OFF_CTRL = "settings.screen_off_control";
    public static final String APP_THEME = "settings.app_theme";
    public static final String GET_THEMES = "settings.get_themes";
    public static final String THEMES = "settings.themes";
    public static final String HOME_MORE = "settings.home_more";
    public static final String HOME_MANAGE_MORE = "settings.home_manage_more";
    public static final String APPEARANCE = "settings.appearance";
    public static final String APPEARANCE_STATUS = "settings.appearance.status";
    public static final String APPEARANCE_LAYOUT = "settings.appearance.layout";
    public static final String STATUS_BAR_LEFT = "settings.status_bar_left";
    public static final String STATUS_BAR_MATCH_FONT = "settings.status_bar_match_font";
    public static final String NOW_PLAYING_MATCH_FONT = "settings.now_playing_match_font";
    public static final String NOW_PLAYING_BACKDROP = "settings.now_playing_backdrop";
    public static final String NOW_PLAYING_LCD_ART = "settings.now_playing_lcd_art";
    public static final String NOW_PLAYING_3D_ALBUM_ART = "settings.now_playing_3d_album_art";
    public static final String SCREEN_TIMEOUT = "settings.screen_timeout";
    public static final String FULL_WIDTH = "settings.full_width";
    public static final String MENU_TRANSITIONS = "settings.menu_transitions";
    public static final String POWER_OFF = "settings.power_off";
    public static final String POWER_RESTART = "settings.power_restart";
    public static final String POWER_SAVING_SHUTDOWN = "settings.power_saving_shutdown";
    public static final String WIFI_SLEEP_POWER_OFF = "settings.wifi_sleep_power_off";
    public static final String DEVICE = "settings.device";
    public static final String LIBRARY = "settings.library";
    public static final String MEDIA = "settings.media";
    public static final String POWER = "settings.power";
    public static final String USB = "settings.usb";
    public static final String USB_AUTO_CONNECT = "settings.usb_auto_connect";
    public static final String USB_SUPPRESS_PROMPT = "settings.usb_suppress_prompt";
    public static final String USB_TURN_ON = "settings.usb_turn_on";
    public static final String SWITCH_ROCKBOX = "settings.switch_rockbox";
    public static final String RESET = "settings.reset";
    public static final String RESET_ROCKBOX = "settings.reset.rockbox";
    public static final String RESET_SOLAR = "settings.reset.solar";
    public static final String RESET_THEMES = "settings.reset.themes";
    public static final String RESET_MICROSD = "settings.reset.microsd";
    public static final String RESET_CACHES = "settings.reset.caches";
    public static final String RESET_EVERYTHING = "settings.reset.everything";
    public static final String RESET_CONTINUE = "settings.reset.continue";
    public static final String WEB_SERVER = "settings.web_server";
    public static final String CONNECTIONS = "settings.connections";
    public static final String WIFI_SETUP = "settings.wifi_setup";
    public static final String REACH = "settings.reach";
    public static final String SOULSEEK = "settings.soulseek";
    public static final String DEEZER = "settings.deezer";
    public static final String AUTO_FETCH = "settings.auto_fetch";
    public static final String LIBRARY_BROWSE = "settings.library_browse";
    public static final String LIB_SPLIT_CREDITS = "library.split_credits";
    public static final String LIB_NORM_ALBUM = "library.norm_album";
    public static final String LIB_GUEST_MODE = "library.guest_mode";
    public static final String LIB_ARTIST_FILTER = "library.artist_filter";
    public static final String LIB_ARTIST_SORT = "library.artist_sort";
    public static final String LIB_SONG_SORT = "library.song_sort";
    public static final String LIB_ALBUM_SONG_SORT = "library.album_song_sort";
    public static final String LIB_ALBUM_RACK_SORT = "library.album_rack_sort";
    public static final String LIB_ALBUM_SUB = "library.album_sub";
    public static final String LIB_GUEST_SUB = "library.guest_sub";
    public static final String ABOUT = "settings.about";
    public static final String REPORT_PROBLEM = "settings.report_problem";
    public static final String CONTACT_DEVELOPER = "settings.contact_developer";
    public static final String DIAG_AUTO_REPORT = "settings.diag_auto_report";
    public static final String REPORT_FROM_DEVICE = "settings.report_from_device";
    public static final String DEBUG = "settings.debug";
    public static final String DEBUG_JJ_THEMES = "settings.debug.jj_themes";
    public static final String DEBUG_SHOW_ERROR_TOASTS = "settings.debug.show_error_toasts";
    public static final String DEBUG_DEV_SUPPORT_EXPERIMENT = "settings.debug.dev_support_experiment";
    public static final String DEBUG_RADIO_EXPERIMENT = "settings.debug.radio_experiment";
    public static final String DEBUG_BLUETOOTH_EXPERIMENT = "settings.debug.bluetooth_experiment";
    public static final String DEBUG_FLOW_ENABLED = "settings.debug.flow_enabled";
    public static final String DEBUG_FLOW_OK_LIBRARY = "settings.debug.flow_ok_library";
    public static final String DEBUG_FLOW_THEME = "settings.debug.flow_theme";
    public static final String DEBUG_FLOW_NO_REFLECTIONS = "settings.debug.flow_no_reflections";
    /** Root Settings — master Flow on/off (experimental toggles stay under Debug → Flow). */
    public static final String FLOW = "settings.flow_enabled";
    public static final String FLOW_SETTINGS = "settings.flow";
    public static final String FLOW_MULTI_TRACK_ALBUMS = "settings.flow.multi_track_albums";
    public static final String ARTWORK_PERSPECTIVE = "settings.artwork_perspective";
    public static final String SYSTEM_UPDATE = "settings.system_update";
    public static final String BLUETOOTH_SETUP = "settings.bluetooth_setup";
    public static final String BRIGHTNESS = "settings.brightness";
    public static final String STORAGE = "settings.storage";
    public static final String BACKGROUND = "settings.background";
    public static final String NOW_PLAYING = "settings.now_playing";
    public static final String NOW_PLAYING_ALBUM_BLUR = "settings.now_playing.album_blur";
    public static final String CLEAR_CACHE = "settings.clear_cache";
    public static final String DATETIME = "settings.datetime";
    public static final String LANGUAGE = "settings.language";
    public static final String RADIO = "settings.radio";
    public static final String VIDEO = "settings.video";
    public static final String HOME_SCREEN = "settings.home_screen";
    public static final String SOULSEEK_SEARCH = "soulseek.search";
    public static final String SOULSEEK_ACCOUNT = "soulseek.account";
    public static final String SOULSEEK_CONNECTION = "soulseek.connection";
    public static final String SOULSEEK_ABOUT = "soulseek.about";
    public static final String SOULSEEK_REGENERATE = "soulseek.regenerate";
    public static final String SOULSEEK_HIDE_HIGH_BITRATE = "soulseek.hide_high_bitrate";
    public static final String SOULSEEK_SHARING = "soulseek.sharing";
    public static final String SOULSEEK_REACH_ENABLED = "soulseek.reach_enabled";
    public static final String SOULSEEK_ENABLED = "soulseek.enabled";
    public static final String SOULSEEK_INCLUDE_GET_MUSIC = "soulseek.include_get_music";
    public static final String SOULSEEK_MESSAGING = "soulseek.messaging";
    public static final String SOULSEEK_FIND_USER = "soulseek.find_user";
    public static final String SOULSEEK_FIND_REACH = "soulseek.find_reach";
    public static final String SOULSEEK_MESSAGES = "soulseek.messages";
    public static final String SOULSEEK_CHAT_ROOMS = "soulseek.chat_rooms";
    public static final String SOULSEEK_INTERESTS = "soulseek.interests";
    public static final String DEEZER_SEARCH = "deezer.search";
    public static final String DEEZER_ACCOUNT = "deezer.account";
    public static final String DEEZER_CONNECTION = "deezer.connection";
    public static final String DEEZER_ENABLED = "deezer.enabled";
    public static final String DEEZER_INCLUDE_GET_MUSIC = "deezer.include_get_music";
    public static final String DEEZER_CLEAR = "deezer.clear";
    public static final String DEEZER_SETUP_PC = "deezer.setup_pc";
    public static final String DEEZER_QUALITY = "deezer.quality";
    public static final String WIDGET_CLOCK = "widget.clock";
    public static final String WIDGET_BATTERY = "widget.battery";
    public static final String WIDGET_ALBUM = "widget.album";
    public static final String HOME_ARRANGE = "home.arrange";
    public static final String MORE_MENU = "settings.more_menu";
    public static final String BG_SOURCE = "background.source";
    public static final String BG_SELECT = "background.select";
    public static final String BG_CLEAR = "background.clear";
    public static final String BT_POWER = "bluetooth.power";
    public static final String WIFI_POWER = "wifi.power";
    public static final String UPDATE_CURRENT = "update.current";
    public static final String UPDATE_STABLE = "update.stable";
    public static final String UPDATE_NIGHTLY = "update.nightly";
    public static final String UPDATE_LATEST = "update.latest";
    public static final String DT_YEAR = "datetime.year";
    public static final String DT_MONTH = "datetime.month";
    public static final String DT_DAY = "datetime.day";
    public static final String DT_HOUR = "datetime.hour";
    public static final String DT_MINUTE = "datetime.minute";
    public static final String LANG_SYSTEM = "language.system";
    public static final String LANG_EN = "language.en";
    public static final String LANG_KO = "language.ko";

    public static String homeShortcut(String id) {
        return "home.shortcut." + id;
    }

    public static int labelResId(String rowKey) {
        if (rowKey == null) return 0;
        if (rowKey.startsWith("home.shortcut.")) {
            String id = rowKey.substring("home.shortcut.".length());
            HomeMenuConfig.Entry e = HomeMenuConfig.find(id);
            return e != null ? e.labelResId : 0;
        }
        if (SHUFFLE.equals(rowKey)) return R.string.settings_shuffle_mode;
        if (REPEAT.equals(rowKey)) return R.string.settings_repeat_mode;
        if (EQ.equals(rowKey)) return R.string.settings_equalizer;
        if (PLAYBACK.equals(rowKey)) return R.string.settings_playback;
        if (BUTTON_SOUND.equals(rowKey)) return R.string.settings_button_sound;
        if (BUTTON_VIBRATE.equals(rowKey)) return R.string.settings_button_vibrate;
        if (SCREEN_OFF_CTRL.equals(rowKey)) return R.string.settings_screen_off_control;
        if (APP_THEME.equals(rowKey)) return R.string.settings_app_theme;
        if (GET_THEMES.equals(rowKey) || THEMES.equals(rowKey)) return R.string.settings_themes;
        if (STATUS_BAR_LEFT.equals(rowKey)) return R.string.settings_status_bar_text;
        if (APPEARANCE.equals(rowKey)) return R.string.settings_appearance;
        if (APPEARANCE_STATUS.equals(rowKey)) return R.string.settings_appearance_status;
        if (APPEARANCE_LAYOUT.equals(rowKey)) return R.string.settings_appearance_layout;
        if (STATUS_BAR_MATCH_FONT.equals(rowKey)) return R.string.settings_status_bar_match_font;
        if (NOW_PLAYING_MATCH_FONT.equals(rowKey)) return R.string.settings_now_playing_match_font;
        if (NOW_PLAYING_BACKDROP.equals(rowKey)) return R.string.settings_now_playing_backdrop;
        if (NOW_PLAYING_LCD_ART.equals(rowKey)) return R.string.settings_now_playing_lcd_art;
        if (ARTWORK_PERSPECTIVE.equals(rowKey)) return R.string.settings_artwork_perspective;
        if (NOW_PLAYING_3D_ALBUM_ART.equals(rowKey)) return R.string.settings_now_playing_3d_album_art;
        if (SCREEN_TIMEOUT.equals(rowKey)) return R.string.settings_screen_timeout;
        if (FULL_WIDTH.equals(rowKey)) return R.string.settings_full_width_menus;
        if (MENU_TRANSITIONS.equals(rowKey)) return R.string.settings_menu_transitions;
        if (POWER_OFF.equals(rowKey)) return R.string.settings_power_off;
        if (POWER_RESTART.equals(rowKey)) return R.string.settings_power_restart;
        if (POWER_SAVING_SHUTDOWN.equals(rowKey)) return R.string.settings_power_saving_shutdown;
        if (WIFI_SLEEP_POWER_OFF.equals(rowKey)) return R.string.settings_wifi_sleep_power_off;
        if (DEVICE.equals(rowKey)) return R.string.settings_device;
        if (LIBRARY.equals(rowKey)) return R.string.settings_library;
        if (MEDIA.equals(rowKey)) return R.string.settings_media;
        if (POWER.equals(rowKey)) return R.string.settings_power;
        if (USB.equals(rowKey)) return R.string.settings_usb;
        if (USB_AUTO_CONNECT.equals(rowKey)) return R.string.settings_usb_auto_connect;
        if (USB_SUPPRESS_PROMPT.equals(rowKey)) return R.string.settings_usb_suppress_prompt;
        if (USB_TURN_ON.equals(rowKey)) return R.string.settings_usb_turn_on;
        if (SWITCH_ROCKBOX.equals(rowKey)) return R.string.settings_switch_rockbox;
        if (RESET.equals(rowKey)) return R.string.settings_reset;
        if (RESET_ROCKBOX.equals(rowKey)) return R.string.settings_reset_rockbox;
        if (RESET_SOLAR.equals(rowKey)) return R.string.settings_reset_solar;
        if (RESET_THEMES.equals(rowKey)) return R.string.settings_reset_themes;
        if (RESET_MICROSD.equals(rowKey)) return R.string.settings_reset_microsd;
        if (RESET_CACHES.equals(rowKey)) return R.string.settings_reset_caches;
        if (RESET_EVERYTHING.equals(rowKey)) return R.string.settings_reset_everything;
        if (RESET_CONTINUE.equals(rowKey)) return R.string.settings_reset_continue;
        if (WEB_SERVER.equals(rowKey)) return R.string.settings_web_server;
        if (CONNECTIONS.equals(rowKey)) return R.string.settings_connections;
        if (WIFI_SETUP.equals(rowKey)) return R.string.settings_wifi_setup;
        if (REACH.equals(rowKey)) return R.string.settings_reach;
        if (SOULSEEK.equals(rowKey)) return R.string.settings_soulseek;
        if (DEEZER.equals(rowKey)) return R.string.settings_deezer;
        if (AUTO_FETCH.equals(rowKey)) return R.string.settings_auto_fetch;
        if (LIBRARY_BROWSE.equals(rowKey)) return R.string.settings_library_browse;
        if (LIB_SPLIT_CREDITS.equals(rowKey)) return R.string.lib_split_credits;
        if (LIB_NORM_ALBUM.equals(rowKey)) return R.string.lib_norm_album_case;
        if (LIB_GUEST_MODE.equals(rowKey)) return R.string.lib_guest_browse;
        if (LIB_ARTIST_FILTER.equals(rowKey)) return R.string.lib_artist_filter;
        if (LIB_ARTIST_SORT.equals(rowKey)) return R.string.lib_artist_sort;
        if (LIB_SONG_SORT.equals(rowKey)) return R.string.lib_song_sort;
        if (LIB_ALBUM_SONG_SORT.equals(rowKey)) return R.string.lib_album_song_sort;
        if (LIB_ALBUM_SUB.equals(rowKey)) return R.string.lib_album_owner_sub;
        if (LIB_GUEST_SUB.equals(rowKey)) return R.string.lib_guest_song_sub;
        if (ABOUT.equals(rowKey)) return R.string.settings_about;
        if (REPORT_PROBLEM.equals(rowKey)) return R.string.settings_report_problem;
        if (CONTACT_DEVELOPER.equals(rowKey)) return R.string.settings_contact_developer;
        if (DIAG_AUTO_REPORT.equals(rowKey)) return R.string.settings_diag_auto_report;
        if (REPORT_FROM_DEVICE.equals(rowKey)) return R.string.settings_report_from_device;
        if (DEBUG.equals(rowKey)) return R.string.settings_sub_debug;
        if (DEBUG_JJ_THEMES.equals(rowKey)) return R.string.settings_debug_jj_themes;
        if (DEBUG_SHOW_ERROR_TOASTS.equals(rowKey)) return R.string.settings_debug_show_error_toasts;
        if (DEBUG_DEV_SUPPORT_EXPERIMENT.equals(rowKey)) return R.string.settings_debug_dev_support_experiment;
        if (DEBUG_RADIO_EXPERIMENT.equals(rowKey)) return R.string.settings_debug_radio_experiment;
        if (DEBUG_BLUETOOTH_EXPERIMENT.equals(rowKey)) return R.string.settings_debug_bluetooth_experiment;
        if (DEBUG_FLOW_ENABLED.equals(rowKey)) return R.string.settings_debug_flow_enabled;
        if (DEBUG_FLOW_OK_LIBRARY.equals(rowKey)) return R.string.settings_debug_flow_ok_library;
        if (DEBUG_FLOW_THEME.equals(rowKey)) return R.string.settings_debug_flow_theme;
        if (DEBUG_FLOW_NO_REFLECTIONS.equals(rowKey)) return R.string.settings_debug_flow_no_reflections;
        if (FLOW.equals(rowKey)) return R.string.settings_flow;
        if (FLOW_SETTINGS.equals(rowKey)) return R.string.settings_sub_flow;
        if (FLOW_MULTI_TRACK_ALBUMS.equals(rowKey)) return R.string.settings_flow_multi_track_albums;
        if (SYSTEM_UPDATE.equals(rowKey)) return R.string.settings_app_version;
        if (BLUETOOTH_SETUP.equals(rowKey)) return R.string.settings_bluetooth_setup;
        if (BRIGHTNESS.equals(rowKey)) return R.string.settings_display_brightness;
        if (STORAGE.equals(rowKey)) return R.string.settings_storage_info;
        if (BACKGROUND.equals(rowKey)) return R.string.settings_background;
        if (NOW_PLAYING.equals(rowKey)) return R.string.settings_now_playing;
        if (NOW_PLAYING_ALBUM_BLUR.equals(rowKey)) return R.string.settings_player_album_blur;
        if (CLEAR_CACHE.equals(rowKey)) return R.string.settings_clear_cache;
        if (DATETIME.equals(rowKey)) return R.string.settings_datetime;
        if (LANGUAGE.equals(rowKey)) return R.string.settings_language;
        if (RADIO.equals(rowKey)) return R.string.settings_sub_radio;
        if (VIDEO.equals(rowKey)) return R.string.settings_sub_video;
        if (MediaSuiteHost.ROW_AUTO_DETECT.equals(rowKey)) return R.string.radio_settings_auto_region;
        if (MediaSuiteHost.ROW_BUFFER_SD.equals(rowKey)) return R.string.radio_settings_buffer_sd;
        if (MediaSuiteHost.ROW_VIDEO_SLEEP.equals(rowKey)) return R.string.video_settings_sleep_during_playback;
        if (HOME_SCREEN.equals(rowKey)) return R.string.home_screen_editor;
        if (SOULSEEK_SEARCH.equals(rowKey)) return R.string.soulseek_search_row;
        if (SOULSEEK_ACCOUNT.equals(rowKey)) return R.string.soulseek_account_row;
        if (SOULSEEK_CONNECTION.equals(rowKey)) return R.string.soulseek_menu_connection;
        if (SOULSEEK_ABOUT.equals(rowKey)) return R.string.soulseek_menu_about;
        if (SOULSEEK_REGENERATE.equals(rowKey)) return R.string.soulseek_regenerate_account;
        if (SOULSEEK_HIDE_HIGH_BITRATE.equals(rowKey)) return R.string.soulseek_hide_high_bitrate;
        if (SOULSEEK_SHARING.equals(rowKey)) return R.string.soulseek_share_library;
        if (SOULSEEK_REACH_ENABLED.equals(rowKey)) return R.string.soulseek_reach_enabled;
        if (SOULSEEK_ENABLED.equals(rowKey)) return R.string.soulseek_enabled;
        if (SOULSEEK_INCLUDE_GET_MUSIC.equals(rowKey)) return R.string.get_music_include_reach;
        if (SOULSEEK_MESSAGING.equals(rowKey)) return R.string.soulseek_allow_messaging;
        if (SOULSEEK_FIND_USER.equals(rowKey)) return R.string.soulseek_find_user;
        if (SOULSEEK_FIND_REACH.equals(rowKey)) return R.string.soulseek_find_reach_users;
        if (SOULSEEK_MESSAGES.equals(rowKey)) return R.string.soulseek_messages;
        if (SOULSEEK_CHAT_ROOMS.equals(rowKey)) return R.string.soulseek_chat_rooms;
        if (DEEZER_SEARCH.equals(rowKey)) return R.string.deezer_search_row;
        if (DEEZER_ACCOUNT.equals(rowKey)) return R.string.deezer_account_row;
        if (DEEZER_CONNECTION.equals(rowKey)) return R.string.deezer_connection_row;
        if (DEEZER_ENABLED.equals(rowKey)) return R.string.deezer_enabled;
        if (DEEZER_INCLUDE_GET_MUSIC.equals(rowKey)) return R.string.get_music_include_deezer;
        if (DEEZER_CLEAR.equals(rowKey)) return R.string.deezer_clear_account;
        if (DEEZER_SETUP_PC.equals(rowKey)) return R.string.deezer_setup_pc;
        if (DEEZER_QUALITY.equals(rowKey)) return R.string.deezer_quality;
        if (WIDGET_CLOCK.equals(rowKey)) return R.string.widget_clock;
        if (WIDGET_BATTERY.equals(rowKey)) return R.string.widget_battery;
        if (WIDGET_ALBUM.equals(rowKey)) return R.string.widget_album;
        if (HOME_ARRANGE.equals(rowKey)) return R.string.home_screen_arrange;
        if (HOME_MORE.equals(rowKey)) return R.string.home_screen_more;
        if (HOME_MANAGE_MORE.equals(rowKey)) return R.string.home_screen_manage_more;
        if (MORE_MENU.equals(rowKey)) return R.string.home_menu_more;
        if (BG_SOURCE.equals(rowKey)) return R.string.settings_background_source;
        if (BG_SELECT.equals(rowKey)) return R.string.settings_select_background;
        if (BG_CLEAR.equals(rowKey)) return R.string.settings_clear_background;
        if (BT_POWER.equals(rowKey)) return R.string.bluetooth_power;
        if (WIFI_POWER.equals(rowKey)) return R.string.wifi_power;
        if (UPDATE_CURRENT.equals(rowKey)) return R.string.update_current_version;
        if (UPDATE_STABLE.equals(rowKey)) return R.string.update_latest_stable;
        if (UPDATE_NIGHTLY.equals(rowKey)) return R.string.update_latest_nightly;
        if (UPDATE_LATEST.equals(rowKey)) return R.string.update_latest_version;
        if (DT_YEAR.equals(rowKey)) return R.string.datetime_year;
        if (DT_MONTH.equals(rowKey)) return R.string.datetime_month;
        if (DT_DAY.equals(rowKey)) return R.string.datetime_day;
        if (DT_HOUR.equals(rowKey)) return R.string.datetime_hour;
        if (DT_MINUTE.equals(rowKey)) return R.string.datetime_minute;
        if (LANG_SYSTEM.equals(rowKey)) return R.string.language_system;
        if (LANG_EN.equals(rowKey)) return R.string.language_english;
        if (LANG_KO.equals(rowKey)) return R.string.language_korean;
        return 0;
    }

    private RowKeys() {}
}
